### ISSUE TITLE
evil-search-highlight-persist-remove-all is not interactive anymore

### ISSUE THREAD

**Issue by rcoedo** [naclander/evil-search-highlight-persist#3]
Hi!

This change breaks part of the functionality. C-x <SPC> keybinding now throws an error.

Thanks!

**Comment by naclander** [comment]
Thanks for reporting this!

**Comment by naclander** [comment]
I accidentally removed `(interactive)` from evil-search-highlight-persist-remove-all at some point. Sorry about that, I'll add it back in.

**Comment by naclander** [comment]
Fixed with https://github.com/naclander/evil-search-highlight-persist/commit/6e04a8c075f5fd62526d222447048faab8bfa187

Let me know if you have any other issues.

**Comment by rcoedo** [comment]
Thanks for fixing this and for maintaining this awesome package 🍻
